# Generated by Django 6.0 on 2026-01-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(help_text="7XXXXXXXXXX", max_length=15, unique=True, verbose_name="Номер телефона"),
        ),
    ]
